# Site settings
title: Paolo C.
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# The subpath of your site, e.g. /blog
baseurl: ""
# The base hostname and protocol for your site
url: "http://painl.es"
exclude: [excluded, README.md, LICENSE, Gemfile]
permalink: pretty
disqus_shortname: painl.es

# Build settings
markdown: kramdown
timezone: Europe/Brussels
kramdown:
  input: GFM  # Github Flavored Markdown

# Defaults
defaults:
  -  # Set the defaults for posts
    scope: 
      path: ""  # folder name or part of the url; empty means all posts.
      type: "posts"  # pages or posts or drafts or a collection; optional.
    values: &DEFAULTS_POSTS_VAL  # &DEFAULTS_POSTS_VAL defines a node anchor
      layout: post
      title: "This is Paolo C."
      excerpt: "Paolo C.: Software Egineer. Python, Django, FOSS, Google GSoC, Moogle, Promptastic."
      tags: ["paolo c.", "software engineer", "web development", "python", "django", "foss", "gsoc", "moogle", "promptastic", "neurostar", "biostar"]
      comments: true
      pagination: true
      ogtype: article
      ogimage: "/assets/img/site-logos/7.png"
      cssfile: "/assets/css/post.css"
  -  # Set the defaults for drafts (keep them the same as for posts)
    scope:
      path: ""  # folder name or part of the url; empty means all posts.
      type: "drafts"  # pages or posts or drafts or a collection; optional.
    values: *DEFAULTS_POSTS_VAL  # Reference to the &DEFAULTS_POSTS_VAL node anchor
  -  # Set the defaults for pages
    scope:
      path: ""  # folder name or part of the url; empty means all posts.
      type: "pages"  # pages or posts or drafts or a collection; optional.
    values:
      <<: *DEFAULTS_POSTS_VAL  # Reference to the &DEFAULTS_POSTS_VAL node anchor w/ modifications
      layout: page
      comments: false
      cssfile: "/assets/css/pages/main.css"